BionicUniversity\Bundle\WallBundle\Entity\Post:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
        text:
            type: text
        createdAt:
            type: datetime
    manyToOne:
        author:
            targetEntity: BionicUniversity\Bundle\UserBundle\Entity\User
            inversedBy: post
        wall:
            targetEntity: BionicUniversity\Bundle\WallBundle\Entity\Wall
            inversedBy: post
    lifecycleCallbacks: {  }
