BionicUniversity\Bundle\WallBundle\Entity\Wall:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        post:
            targetEntity: BionicUniversity\Bundle\WallBundle\Entity\Post
            mappedBy: wall
    oneToOne:
        community:
            targetEntity: BionicUniversity\Bundle\CommunityBundle\Entity\Community