BionicUniversity\Bundle\CommunityBundle\Entity\TaskManager:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
            details:
                type: text
                nullable: true
    oneToMany:
           tasks:
               targetEntity: BionicUniversity\Bundle\CommunityBundle\Entity\Task
               mappedBy: taskManager
    oneToOne:
            projectTask:
                targetEntity: BionicUniversity\Bundle\CommunityBundle\Entity\ProjectTask
                inversedBy: taskManager
    lifecycleCallbacks: {  }
