BionicUniversity\Bundle\CommunityBundle\Entity\Task:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: text
        createdAt:
            type: datetime
    manyToOne:
            taskManager:
                targetEntity: BionicUniversity\Bundle\CommunityBundle\Entity\TaskManager
                inversedBy: tasks
    lifecycleCallbacks: {  }
