BionicUniversity\Bundle\UserBundle\Entity\User:
    repositoryClass: BionicUniversity\Bundle\UserBundle\Doctrine\ORM\UserRepository
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: '50'
        lastName:
            type: string
            length: '50'
        position:
            type: string
            length: '100'
        dateOfBirth:
            type: date
            nullable: true
        gender:
            type: string
            length: '6'
        avatar:
            type: string
            length: '255'
            nullable: true
        aboutMe:
            type: string
            length: '1000'
            nullable: true
        joined:
            type: date
        phoneNumber:
            type: string
            length: '15'
            nullable: true
        status:
            type: string
            length: '140'
            nullable:  true
        tasksCount:
            type: integer
            nullable: true
    manyToMany:
        interests:
            targetEntity: BionicUniversity\Bundle\UserBundle\Entity\Interest
            inversedBy: users
            joinTable:
                name: users_interests
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    interest_id:
                        referencedColumnName: id
    oneToMany:
        incomingMessages:
            targetEntity: BionicUniversity\Bundle\MessageBundle\Entity\Message
            mappedBy: toUser
        outcomingMessages:
            targetEntity: BionicUniversity\Bundle\MessageBundle\Entity\Message
            mappedBy: fromUser
        posts:
            targetEntity: BionicUniversity\Bundle\WallBundle\Entity\Post
            mappedBy: author
        memberships:
            targetEntity: BionicUniversity\Bundle\CommunityBundle\Entity\Membership
            mappedBy: user
            cascade: ['remove']
        requests:
            targetEntity: BionicUniversity\Bundle\UserBundle\Entity\Friendship
            mappedBy: userSender
            cascade: ['remove']
        invites:
            targetEntity: BionicUniversity\Bundle\UserBundle\Entity\Friendship
            mappedBy: userReceiver
            cascade: ['remove']
        myCommunities:
            targetEntity: BionicUniversity\Bundle\CommunityBundle\Entity\Community
            mappedBy: owner
    manyToOne:
        department:
            targetEntity: BionicUniversity\Bundle\UserBundle\Entity\Department
            inversedBy: users
    lifecycleCallbacks: {  }
